//
//  OnbDataTargetSchoolsBusiness.swift
//  Duello
//
//  Répertoire des écoles de commerce visées (clé `ECG` de `TARGET_SCHOOLS`).
//  Porté de : src/data/targetSchools.ts (`BUSINESS_SCHOOLS`).
//
//  Répertoire Onisep Idéo, mise à jour du 21 juillet 2026.
//
//  Données statiques éditoriales, transcrites mot pour mot depuis l'app Expo.
//  Aucune dépendance externe. Cible : iOS 16.
//

import Foundation

/// Écoles de commerce du répertoire Onisep, filière `ECG` de
/// `TARGET_SCHOOLS` (`src/data/targetSchools.ts`). Référencée par
/// `OnbDataTargetSchools`.
enum OnbDataBusinessSchools {
    static let all: [String] = [
        "Alliance européenne - Périgueux Business School",
        "AMOS - Sport Business School, campus de Lille",
        "AMOS - Sport Business School, campus de Lyon",
        "AMOS - Sport Business School, campus de Paris",
        "Ascencia Business School La Défense",
        "Ascencia Business School Marne-la-Vallée",
        "Ascencia Business School Saint-Quentin-en-Yvelines",
        "Ascencia Business School Évry",
        "Audencia Business School",
        "Brest Business School",
        "Burgundy School of Business",
        "Campus Sciences U Lyon",
        "Campus Strat@innov Paris",
        "Campus supérieur de Marseille- École pratique",
        "CCI du Cantal - Le Campus",
        "CCI Formation Puy-de-Dôme",
        "Centre d'études franco-américain de management",
        "Clermont School of Business (ex ESC Clermont BS)",
        "Conservatoire national des arts et métiers Hauts-de-France - centre d'Amiens",
        "EBS Paris",
        "EDC Paris",
        "EDHEC Business School",
        "EKLYA School of Business",
        "EMD Business School",
        "emlyon Business School",
        "ESARC Evolution Montpellier",
        "ESARC Évolution - École de commerce et de vente Campus ENOVA",
        "Esccot Groupe - EFIP",
        "ESCP Business School",
        "ESDES Business School",
        "ESG Aix",
        "ESG Bordeaux",
        "ESG Luxe",
        "ESG Montpellier",
        "ESG Rennes",
        "ESG Sport",
        "ESG Toulouse",
        "ESG Tourisme",
        "ESG Tours",
        "ESICAD - la compagnie de formation",
        "ESID - Nice",
        "ESID Fréjus",
        "ESLSCA Business School Paris",
        "ESSCA School of Management",
        "ESSEC Business School",
        "ESUP Lyon",
        "European School of Administration and Management",
        "Excelia",
        "GEM - Alpine Business School",
        "HEC Paris",
        "ICN Business School",
        "IDRAC Business School",
        "IESEG School of Management",
        "INSEEC",
        "Institut commercial lyonnais",
        "Institut consulaire de formation d'Ajaccio",
        "Institut de formation aux affaires et à la gestion",
        "Institut de management des industries de la santé (groupe IGS)",
        "Institut européen des affaires",
        "Institut international du commerce et du développement - Igensia Education",
        "Institut Lyfe (ex Institut Paul Bocuse)",
        "Institut Mines - Télécom École de Management",
        "Institut supérieur de commerce international de Dunkerque - Côte d'Opale",
        "Institut supérieur de gestion - International Business School",
        "Institut supérieur du commerce automobile du Mans ISCAM",
        "Institut supérieur du commerce de Paris",
        "Institut technique supérieur du management international",
        "International University of Monaco",
        "IPAC - IHECF Ville la Grand",
        "IPAC - IPAC Bachelor Factory - MBway - IHECF - WIN Sport School Le Bourget du Lac",
        "IPAC - Ipac Bachelor Factory - MBway - WIN Sport School",
        "IPAC - WIN Sport School - Albertville",
        "IPAC Bachelor Factory",
        "IPAC Bachelor Factory - Paris Ouest",
        "Ipac Bachelor Factory Angers",
        "IPAG Business School",
        "ISG Paris",
        "ISTEC Paris",
        "ISUGA - École supérieure internationale - CCI Finistère",
        "Kedge Business School",
        "MBA ESG Paris",
        "MBway",
        "MBway Angers",
        "MBway Bordeaux",
        "MBway Caen",
        "MBway Grand Genève",
        "MBway Lille",
        "MBway Lyon",
        "MBway Montpellier",
        "MBway Nantes",
        "MBway Paris Ouest",
        "MBway Rennes",
        "MBway Strasbourg",
        "MBway Toulouse",
        "Montpellier Business School",
        "Negociance Business School",
        "NEOMA Business School",
        "Négoventis - CCI Formation EESC",
        "Paris School of Business",
        "Rennes School of Business",
        "Schiller International University - Paris Campus",
        "SKEMA Business School",
        "South Champagne Business School - Groupe Y Schools",
        "SUP CAREER",
        "Sup de V",
        "Sup' La Mache",
        "TBS Education",
        "The American Business School of Paris - groupe IGS",
        "The School of Advanced Management and Finance",
        "Vatel - campus de Bordeaux Les Chartrons",
        "Vatel - campus de Bordeaux Les Halles",
        "Vatel - campus de Lyon",
        "Vatel - campus de Nîmes",
        "Vatel - campus de Paris",
        "École 3A",
        "École 3A - École supérieure de commerce et développement",
        "École de commerce Besançon",
        "École de commerce de Tahiti",
        "École de commerce durable et responsable",
        "École de commerce et de management de Mulhouse",
        "École de commerce et management - campus de Belfort",
        "École de commerce et management campus de Besançon",
        "École de commerce et management campus de Dijon",
        "École de commerce Montbéliard",
        "École de commerce Pontarlier",
        "École de commerce Vesoul",
        "École de gestion et de commerce - Sud Management Business School",
        "École de gestion et de commerce CCI Nord-Isère",
        "École de gestion et de commerce Centre Est",
        "École de gestion et de commerce d'Occitanie",
        "École de gestion et de commerce de Blois",
        "École de gestion et de commerce de Brive",
        "École de gestion et de commerce de Guadeloupe",
        "École de gestion et de commerce de Guyane",
        "École de gestion et de commerce de La Réunion",
        "École de gestion et de commerce de Lille",
        "École de gestion et de commerce de Martinique",
        "École de gestion et de commerce de Montauban",
        "École de gestion et de commerce de Montluçon",
        "École de gestion et de commerce de Normandie",
        "École de gestion et de commerce de Nîmes",
        "École de gestion et de commerce de Poitiers",
        "École de gestion et de commerce de Rodez",
        "École de gestion et de commerce de Sens",
        "École de gestion et de commerce de Valence",
        "École de gestion et de commerce du Mans",
        "École de gestion et de commerce du Pacifique Sud",
        "École de gestion et de commerce Le Puy-en-Velay",
        "École de Management Appliqué",
        "École de management commercial de Lons-Le-Saunier",
        "École de management de Normandie",
        "École de management de Strasbourg",
        "École de management en alternance de Paris",
        "École de management Léonard de Vinci",
        "École supérieure de commerce d'Amiens",
        "École supérieure de commerce d'Annecy",
        "École supérieure de commerce de Compiègne",
        "École supérieure de commerce de Limoges",
        "École supérieure de commerce des 3 frontières",
        "École supérieure de commerce des entrepreneurs de la naturalité",
        "École supérieure de commerce et d'économie numérique",
        "École supérieure de commerce et de communication - ESCC Business School",
        "École supérieure de commerce et de gestion",
        "École supérieure de commerce et de gestion de Mayotte",
        "École supérieure de commerce et management Colmar",
        "École supérieure de commerce et management Strasbourg",
        "École supérieure de commerce international",
        "École supérieure de gestion et commerce international - Pôle ESG",
        "École supérieure de gestion et finance - Pôle ESG",
        "École supérieure de management des Landes",
        "École supérieure de management en alternance - groupe Hema",
        "École Supérieure de Tourisme - Groupe Y Schools",
        "École supérieure de vente et d'exportation",
        "École supérieure des technologies et des affaires de Belfort",
        "École supérieure du commerce extérieur",
        "Éklore-ed",
        "Éklore-ed School of Management",
    ]
}
