//
//  OnbDataTargetSchoolsEngineering.swift
//  Duello
//
//  Répertoire des écoles d'ingénieurs visées (clé `MPSI` de `TARGET_SCHOOLS`).
//  Porté de : src/data/targetSchools.ts (`ENGINEERING_SCHOOLS`).
//
//  Répertoire Onisep Idéo, mise à jour du 21 juillet 2026.
//
//  Données statiques éditoriales, transcrites mot pour mot depuis l'app Expo.
//  Aucune dépendance externe. Cible : iOS 16.
//

import Foundation

/// Écoles d'ingénieurs du répertoire Onisep, filière `MPSI` de
/// `TARGET_SCHOOLS` (`src/data/targetSchools.ts`). Référencée par
/// `OnbDataTargetSchools`.
enum OnbDataEngineeringSchools {
    static let all: [String] = [
        "3iL Ingénieurs - site de Limoges",
        "3iL Ingénieurs - site de Nantes",
        "3iL Ingénieurs - site de Rodez",
        "AgroParisTech - Centre d'Orléans",
        "AgroParisTech - Centre de Clermont-Ferrand",
        "AgroParisTech - Centre de Montpellier",
        "AgroParisTech - Centre de Nancy",
        "AgroParisTech - Centre de Paris-Saclay",
        "Builders École d'ingénieurs - site de Caen (ex ESITC Caen)",
        "Builders École d'ingénieurs - site de Lyon (exESITC Lyon)",
        "Campus Supérieur de Marseille - ISBA TP",
        "Centrale Lyon ENISE (École nationale d'ingénieurs de Saint-Étienne de l'École centrale de Lyon)",
        "Centrale Méditerranée - campus de Marseille",
        "Centrale Méditerranée - Campus de Nice",
        "CentraleSupélec - campus de Metz",
        "CentraleSupélec - campus de Paris-Saclay",
        "CentraleSupélec - campus de Rennes",
        "Centre des hautes études de la construction",
        "CESI école d'ingénieurs - campus d'Aix-en-Provence",
        "CESI école d'ingénieurs - campus d'Angoulême",
        "CESI école d'ingénieurs - campus d'Arras",
        "CESI école d'ingénieurs - campus d'Orléans",
        "CESI école d'ingénieurs - campus d'Orléans - site de Tours",
        "CESI école d'ingénieurs - campus de Bordeaux",
        "CESI école d'ingénieurs - campus de Brest",
        "CESI école d'ingénieurs - campus de Caen",
        "CESI école d'ingénieurs - campus de Dijon",
        "CESI école d'ingénieurs - campus de Grenoble",
        "CESI école d'ingénieurs - campus de La Rochelle",
        "CESI école d'ingénieurs - campus de Lille",
        "CESI école d'ingénieurs - campus de Lyon",
        "CESI école d'ingénieurs - campus de Montpellier",
        "CESI école d'ingénieurs - campus de Nancy",
        "CESI école d'ingénieurs - campus de Nantes",
        "CESI école d'ingénieurs - campus de Nice",
        "CESI école d'ingénieurs - campus de Paris Nanterre",
        "CESI école d'ingénieurs - campus de Pau",
        "CESI école d'ingénieurs - campus de Pau - site d'Assat",
        "CESI école d'ingénieurs - campus de Reims",
        "CESI école d'ingénieurs - campus de Rouen",
        "CESI école d'ingénieurs - campus de Saint-Nazaire",
        "CESI école d'ingénieurs - campus de Strasbourg",
        "CESI école d'ingénieurs - campus de Toulouse",
        "CESI école d'ingénieurs - campus du Mans",
        "CY Tech - campus de Cergy",
        "CY Tech - campus de Pau",
        "ECAM Louis de Broglie - campus de Cherbourg-en-Cotentin",
        "ECAM Louis de Broglie - campus de Rennes",
        "ECAM-EPMI - site de Cachan",
        "ECAM-EPMI - site de Cergy",
        "ECAM-EPMI - site de Grasse",
        "EFREI Paris - campus de Bordeaux",
        "EFREI Paris - campus de Villejuif",
        "EICnam Bourgogne Franche-Comté - site de Chalon-sur-Saône",
        "EICnam Bretagne - Institut Boussingault",
        "EICnam Grand Est - site de Metz",
        "EICnam Grand Est - site de Nancy",
        "EICnam Grand Est - site de Reims",
        "EICnam Grand Est - site de Saint-Dié-des-Vosges",
        "EICnam Grand Est - site de Strasbourg",
        "EICnam Grand Est - UIMM Alsace - site d'Eckbolsheim",
        "EICnam Hauts-de-France - PROMEO - site de Beauvais",
        "EICnam Hauts-de-France - site d'Amiens",
        "EICnam Normandie - ITII Normandie",
        "EICnam Nouvelle Aquitaine - site de Châtellerault",
        "EICnam Nouvelle-Aquitaine - site d'Angoulême",
        "EICnam Nouvelle-Aquitaine - site de Limoges",
        "EICnam Nouvelle-Aquitaine - site de Niort",
        "EICnam Nouvelle-Aquitaine - site de Poitiers",
        "EICnam PACA - site d'Avignon - Académie Vaucluse Provence",
        "EICnam PACA - site de Toulon",
        "EICnam Paris et Ile-de-France - campus de Mantes-la-Jolie",
        "EICnam Paris et Ile-de-France - campus de Mantes-la-Ville",
        "EICnam Paris et Ile-de-France - campus de Paris",
        "EICnam Paris et Ile-de-France - campus de Saint-Denis",
        "EICnam Pays-de-la-Loire - site de La Roche-sur-Yon",
        "ENS d'électrotechnique, électronique, informatique, hydraulique, télécommunications - Toulouse INP",
        "ENS pour la performance industrielle et la maintenance aéronautique",
        "ENSCL - École Nationale Supérieure de Chimie de Lille",
        "ENSIL-ENSCI - site d'Egletons",
        "ENSIL-ENSCI - site de Brive",
        "ENSIL-ENSCI - site de Limoges",
        "ENTPE Lyon",
        "EPF école d'ingénieurs généralistes - site de Montpellier",
        "EPF école d'ingénieurs généralistes - site de Paris-Cachan",
        "EPF école d'ingénieurs généralistes - site de Saint-Nazaire",
        "EPF école d'ingénieurs généralistes - site de Troyes",
        "ESIEE Paris",
        "ESIEE-IT - École d'ingénieurs - CCI Paris Ile de France Éducation - site de Pontoise",
        "ESIEE-IT - École d'ingénieurs - CCI Paris Ile-de-France Éducation - site de Paris",
        "ESIGELEC - site de Poitiers",
        "ESIGELEC - site de Rouen",
        "ESME - campus d'Ivry-sur-Seine",
        "ESME - campus de Bordeaux",
        "ESME - campus de Lille",
        "ESME - campus de Lyon",
        "ESME - campus de Paris",
        "ESTP - Grande école d'ingénieurs de la construction - campus d'Orléans",
        "ESTP - Grande école d'ingénieurs de la construction - campus de Cachan",
        "ESTP - Grande école d'ingénieurs de la construction - campus de Dijon",
        "ESTP - Grande école d'ingénieurs de la construction - campus de Troyes",
        "ESTP - Grande école d'ingénieurs de la construction - ECIR - campus d'Aix-en-Provence",
        "EURECOM",
        "Géodata Paris (ex ENSG-Géomatique)",
        "IG2I - Institut de Génie Informatique et Industriel",
        "Institut Agro Dijon",
        "Institut Agro Montpellier",
        "Institut Agro Rennes-Angers - campus d'Angers",
        "Institut Agro Rennes-Angers - campus de Rennes",
        "Institut catholique d'arts et métiers - site de Bretagne",
        "Institut catholique d'arts et métiers - site de Grand Paris Sud",
        "Institut catholique d'arts et métiers - site de Lille",
        "Institut catholique d'arts et métiers - site de Nantes",
        "Institut catholique d'arts et métiers - site de Strasbourg-Europe",
        "Institut catholique d'arts et métiers - site de Toulouse",
        "Institut catholique d'arts et métiers - site de Vendée",
        "Institut d'optique théorique et appliquée - campus de Bordeaux",
        "Institut d'optique théorique et appliquée - campus de Palaiseau",
        "Institut d'optique théorique et appliquée - campus de Saint-Étienne",
        "Institut en Innovation Logistique",
        "Institut Galilée",
        "Institut national des sciences appliquées - Martinique Caraïbe",
        "Institut national des sciences appliquées Centre-Val de Loire - site de Blois",
        "Institut national des sciences appliquées Centre-Val de Loire - site de Bourges",
        "Institut national des sciences appliquées de Lyon - site de Lyon",
        "Institut national des sciences appliquées de Lyon - site Oyonnax",
        "Institut national des sciences appliquées de Rennes",
        "Institut national des sciences appliquées de Rouen Normandie - site de Rouen",
        "Institut national des sciences appliquées de Rouen Normandie - site du Havre",
        "Institut national des sciences appliquées de Strasbourg",
        "Institut national des sciences appliquées de Toulouse - site de Toulouse",
        "Institut national des sciences appliquées Hauts-de-France",
        "Institut national des sciences et techniques nucléaires",
        "Institut polytechnique des sciences avancées - campus d'Ivry-sur-Seine",
        "Institut polytechnique des sciences avancées - campus de Lyon",
        "Institut polytechnique des sciences avancées - campus de Toulouse",
        "Institut polytechnique UniLaSalle - campus d'Amiens",
        "Institut polytechnique UniLaSalle - campus de Beauvais",
        "Institut polytechnique UniLaSalle - campus de Rennes",
        "Institut polytechnique UniLaSalle - campus de Rouen",
        "Institut supérieur aquitain du bâtiment et des travaux publics",
        "Institut supérieur d'agriculture Rhône-Alpes - campus d'Avignon",
        "Institut supérieur d'agriculture Rhône-Alpes - campus de Lyon",
        "Institut supérieur d'informatique de modélisation et de leurs applications - Clermont Auvergne INP",
        "Institut supérieur d'ingénieurs de Franche-Comté",
        "Institut supérieur d'études logistiques - CFAI Mécavenir - site de Puteaux",
        "Institut supérieur d'études logistiques - site du Havre",
        "Institut supérieur de biotechnologies de Paris - campus de Lyon",
        "Institut supérieur de biotechnologies de Paris - campus de Villejuif",
        "Institut supérieur de l'automobile et des transports - site d'Auxerre",
        "Institut supérieur de l'automobile et des transports - site de Nevers",
        "Institut supérieur de l'aéronautique et de l'espace",
        "Institut supérieur de l'électronique et du numérique Yncréa Méditerranée - campus de Marseille",
        "Institut supérieur de l'électronique et du numérique Yncréa Méditerranée - campus de Toulon",
        "Institut supérieur de l'électronique et du numérique Yncréa Ouest - campus de Brest",
        "Institut supérieur de l'électronique et du numérique Yncréa Ouest - campus de Caen",
        "Institut supérieur de l'électronique et du numérique Yncréa Ouest - campus de Nantes",
        "Institut supérieur de mécanique de Paris",
        "Institut supérieur des matériaux du Mans - ISMANS CESI Le Mans",
        "ISART Digital",
        "ISEL Le Havre - ITII Normandie",
        "Isep - École d'ingénieurs du numérique - site de Bordeaux",
        "Isep - École d'ingénieurs du numérique - site de Paris",
        "Isep - École d'ingénieurs du numérique - site Issy-les-Moulineaux",
        "ISTY UVSQ - campus de Mantes en Yvelines",
        "ISTY UVSQ - campus de Vélizy-Villacoublay",
        "ITECH Lyon",
        "ITEEM",
        "JUNIA Institut supérieur d'agriculture",
        "JUNIA Institut supérieur de l'électronique et du numérique - campus de Bordeaux",
        "JUNIA Institut supérieur de l'électronique et du numérique - campus de Lille",
        "JUNIA École des hautes études d'ingénieur - campus de Châteauroux",
        "JUNIA École des hautes études d'ingénieur - campus de Lille",
        "Mediterranean Institute of Robotics and Automation - Aflokkat Ajaccio",
        "ONIRIS VetAgroBio - Campus des sciences de l'alimentation",
        "Télécom Nancy - Lorraine INP",
        "Télécom Paris",
        "Télécom Physique Strasbourg",
        "Télécom Saint-Étienne - site de Roanne",
        "Télécom Saint-Étienne - site de Saint-Étienne",
        "Télécom SudParis - site d'Évry",
        "Télécom SudParis - site de Palaiseau",
        "Université de technologie de Belfort-Montbéliard - campus de Belfort",
        "Université de technologie de Belfort-Montbéliard - campus de Montbéliard",
        "Université de technologie de Belfort-Montbéliard - campus de Sevenans",
        "Université de technologie de Compiègne",
        "Université de technologie de Troyes - site de Nogent",
        "Université de technologie de Troyes - site de Troyes",
        "Université de Toulouse, sciences, ingénierie et technologie",
        "Université des Antilles Département d'ingénierie",
        "VetAgro Sup - campus agronomique de Clermont",
        "École catholique d'arts et métiers de la Fondation ECAM LaSalle - Lycée La Nativité - site d'Aix-en-Provence",
        "École catholique d'arts et métiers de la Fondation ECAM LaSalle - site de Lyon",
        "École centrale d'électronique - Groupe ECE - campus de Bordeaux",
        "École centrale d'électronique - Groupe ECE - campus de Lyon",
        "École centrale d'électronique - Groupe ECE - campus de Marseille",
        "École centrale d'électronique - Groupe ECE - campus de Paris",
        "École centrale d'électronique - Groupe ECE - campus de Rennes",
        "École Centrale de Lille",
        "École centrale de Lyon",
        "École centrale de Nantes",
        "École d'ingénieur de l'université de Caen - site de Caen",
        "École d'ingénieur informatique et systèmes d'information pour la santé",
        "École d'ingénieurs - Paoli Tech de l'Université de Corse",
        "École d'ingénieurs de l'Artois - site de Béthune",
        "École d'ingénieurs de l'université de Caen - site de Cherbourg-en-Cotentin",
        "École d'ingénieurs de l'université de Toulon",
        "École d'ingénieurs de Purpan",
        "École d'ingénieurs Denis Diderot Paris",
        "École d'ingénieurs des sciences aérospatiales - campus de Bordeaux",
        "École d'ingénieurs des sciences aérospatiales - campus de Saint-Quentin",
        "École d'ingénieurs du littoral Côte d'Opale - site de Boulogne-sur-Mer",
        "École d'ingénieurs du littoral Côte d'Opale - site de Calais",
        "École d'ingénieurs du littoral Côte d'Opale - site de Dunkerque",
        "École d'ingénieurs du littoral Côte d'Opale - site de Saint-Omer Longuenesse",
        "École d'ingénieurs en sciences industrielles et numérique - site de Charleville-Mézières",
        "École d'ingénieurs en sciences industrielles et numérique - site de Reims",
        "École d'ingénieurs en énergies renouvelables",
        "École d'ingénieurs généralistes",
        "École d'ingénieurs Jules Verne - site d'Amiens",
        "École d'ingénieurs Jules Verne - site de Saint-Quentin",
        "École d'ingénieurs SIGMA Clermont - Clermont Auvergne INP",
        "École de biologie industrielle",
        "École de l'air et de l'espace",
        "École des ingénieurs de la ville de Paris",
        "École et observatoire des sciences de la Terre de Strasbourg",
        "École européenne d'ingénieurs en génie des matériaux",
        "École européenne de chimie polymères et matériaux",
        "École internationale du papier, de la communication imprimée et des biomatériaux - Grenoble INP-UGA",
        "École nationale d'ingénieurs de Brest - Bretagne INP",
        "École nationale d'ingénieurs de Metz",
        "École nationale d'ingénieurs de Tarbes",
        "École nationale de l'aviation civile - campus de Montpellier",
        "École nationale de l'aviation civile - campus de Toulouse",
        "École nationale de la météorologie",
        "École nationale de la statistique et de l'administration économique",
        "École nationale de la statistique et de l'analyse de l'information",
        "École nationale des ponts et chaussées - site de Champs-sur-Marne",
        "École nationale du génie de l'eau et de l'environnement de Strasbourg",
        "École nationale supérieure agronomique de Toulouse - Toulouse INP",
        "École nationale supérieure d'agronomie et des industries alimentaires",
        "École nationale supérieure d'arts et métiers - campus Arts et Métiers d'Aix-en-Provence",
        "École nationale supérieure d'arts et métiers - campus Arts et Métiers d'Angers",
        "École nationale supérieure d'arts et métiers - campus Arts et Métiers de Bordeaux Talence",
        "École nationale supérieure d'arts et métiers - campus Arts et Métiers de Chambéry",
        "École nationale supérieure d'arts et métiers - campus Arts et Métiers de Châlons-en-Champagne",
        "École nationale supérieure d'arts et métiers - campus Arts et Métiers de Cluny",
        "École nationale supérieure d'arts et métiers - campus Arts et Métiers de Lille",
        "École nationale supérieure d'arts et métiers - campus Arts et Métiers de Metz",
        "École nationale supérieure d'arts et métiers - campus Arts et Métiers de Paris",
        "École nationale supérieure d'arts et métiers - campus Arts et Métiers de Saint-Étienne - ISTP",
        "École nationale supérieure d'informatique et de mathématiques appliquées - Grenoble INP-UGA",
        "École nationale supérieure d'informatique pour l'industrie et l'entreprise",
        "École nationale supérieure d'ingénieurs de Bretagne Sud - site de Lorient",
        "École nationale supérieure d'ingénieurs de Bretagne Sud - site de Vannes",
        "École nationale supérieure d'ingénieurs de Caen et centre de recherche",
        "École nationale supérieure d'ingénieurs de Poitiers",
        "École nationale supérieure d'ingénieurs de Reims",
        "École nationale supérieure d'ingénieurs du Mans",
        "École nationale supérieure d'ingénieurs Sud Alsace",
        "École nationale supérieure d'électricité et de mécanique",
        "École nationale supérieure d'électronique, informatique, télécommunications, mathématiques et mécanique de Bordeaux",
        "École nationale supérieure de chimie de Montpellier",
        "École nationale supérieure de chimie de Mulhouse",
        "École nationale supérieure de Chimie de Paris - PSL",
        "École nationale supérieure de chimie de Rennes",
        "École nationale supérieure de cognitique",
        "École nationale supérieure de Génie industriel - Grenoble INP-UGA",
        "École nationale supérieure de géologie",
        "École nationale supérieure de l'électronique et de ses applications",
        "École nationale supérieure de l'énergie, l'eau et l'environnement - Grenoble INP-UGA",
        "École nationale supérieure de matériaux, d'agroalimentaire et de chimie",
        "École nationale supérieure de mécanique et d'aérotechnique",
        "École nationale supérieure de mécanique et des microtechniques",
        "École nationale supérieure de physique, électronique, matériaux - Grenoble INP-UGA",
        "École nationale supérieure de techniques avancées - site de Brest",
        "École nationale supérieure de techniques avancées site de Palaiseau",
        "École nationale supérieure de technologie des biomolécules de Bordeaux",
        "École nationale supérieure des arts et industries textiles",
        "École nationale supérieure des industries chimiques",
        "École nationale supérieure des ingénieurs en arts chimiques et technologiques - Toulouse INP",
        "École nationale supérieure des Mines d'Albi - IMT Mines Albi",
        "École nationale supérieure des Mines d'Alès - IMT Mines Alès",
        "École nationale supérieure des Mines de Nancy - Institut supérieur d'ingénierie de la conception - site de Saint-Dié-des-Vosges",
        "École nationale supérieure des Mines de Nancy - site de Nancy",
        "École nationale supérieure des mines de Paris - Campus de Paris",
        "École nationale supérieure des mines de Saint-Étienne - campus de Saint-Étienne",
        "École nationale supérieure des mines de Saint-Étienne - Campus Provence",
        "École nationale supérieure des sciences agronomiques de Bordeaux Aquitaine",
        "École nationale supérieure des sciences applicatives et du risque",
        "École nationale supérieure des sciences appliquées et de technologie",
        "École nationale supérieure des technologies et industries du bois",
        "École nationale supérieure du pétrole et des moteurs",
        "École nationale supérieure en environnement, géoressources et ingénierie du développement durable",
        "École nationale supérieure en génie des systèmes et de l'innovation",
        "École nationale supérieure en génie des technologies industrielles",
        "École nationale supérieure en systèmes avancés et réseaux - Grenoble INP-UGA",
        "École nationale supérieure maritime - site de Marseille",
        "École nationale supérieure maritime - site de Nantes",
        "École nationale supérieure maritime - site du Havre",
        "École nationale supérieure Mines-Télécom Atlantique Bretagne Pays de la Loire - campus de Brest",
        "École nationale supérieure Mines-Télécom Atlantique Bretagne Pays de la Loire - campus de Nantes",
        "École nationale supérieure Mines-Télécom Atlantique Bretagne Pays de la Loire - campus de Rennes",
        "École nationale supérieure Mines-Télécom Nord Europe - campus de Douai",
        "École nationale supérieure Mines-Télécom Nord Europe - campus de Dunkerque",
        "École nationale supérieure Mines-Télécom Nord Europe - campus de Lille",
        "École nationale supérieure Mines-Télécom Nord Europe - InGHénia - campus de Valenciennes",
        "École nationale supérieure Mines-Télécom Nord Europe - Polyvia formation - campus d'Alençon",
        "École navale",
        "École polytechnique",
        "École polytechnique universitaire de Bourgogne (ex ESIREM) - site de Dijon",
        "École polytechnique universitaire de Bourgogne (ex ESIREM) - site du Creusot",
        "École polytechnique universitaire de l'Institut national polytechnique Clermont Auvergne - Clermont Auvergne INP",
        "École polytechnique universitaire de l'université Clermont Auvergne - Clermont Auvergne INP - site de Montluçon",
        "École polytechnique universitaire de l'Université Côte d'Azur",
        "École polytechnique universitaire de l'université d'Aix-Marseille - site de Château Gombert",
        "École polytechnique universitaire de l'université d'Aix-Marseille - site de Luminy",
        "École polytechnique universitaire de l'université d'Aix-Marseille - site de Saint-Jérôme",
        "École polytechnique universitaire de l'université d'Angers",
        "École polytechnique universitaire de l'université d'Orléans - site d'Orléans",
        "École polytechnique universitaire de l'université d'Orléans - site de Chartres",
        "École polytechnique universitaire de l'Université de Lorraine - Polytech Nancy",
        "École polytechnique universitaire de l'université de Montpellier - site de Béziers",
        "École polytechnique universitaire de l'université de Montpellier - site de Montpellier",
        "École polytechnique universitaire de l'université de Montpellier - site de Nîmes",
        "École polytechnique universitaire de l'université de Tours",
        "École polytechnique universitaire de l'université Lille",
        "École polytechnique universitaire de l'Université Lyon - 1 - site de Villeurbanne",
        "École polytechnique universitaire de l'Université Lyon 1 - site de Bourg-en-Bresse",
        "École polytechnique universitaire de l'Université Lyon 1 - site de Roanne",
        "École polytechnique universitaire de l'université Sorbonne Université",
        "École polytechnique universitaire de Nantes Université",
        "École polytechnique universitaire de Paris Saclay",
        "École polytechnique universitaire de Savoie - site d'Annecy",
        "École polytechnique universitaire de Savoie - site de Chambery",
        "École polytechnique universitaire Grenoble INP-UGA",
        "École pour l'informatique et les techniques avancées - site de Lyon",
        "École pour l'informatique et les techniques avancées - site de Rennes",
        "École pour l'informatique et les techniques avancées - site de Strasbourg",
        "École pour l'informatique et les techniques avancées - site de Toulouse",
        "École pour l'informatique et les techniques avancées - site du Kremlin-Bicêtre",
        "École publique d'ingénieurs de la santé et du numérique",
        "École spéciale militaire de Saint-Cyr",
        "École supérieure angevine d'informatique et de productique - site d'Aix-en-Provence",
        "École supérieure angevine d'informatique et de productique - site d'Angers",
        "École supérieure d'agro-développement international",
        "École supérieure d'informatique électronique automatique - campus d'Ivry-sur-Seine",
        "École supérieure d'informatique électronique automatique - campus de Laval",
        "École supérieure d'informatique électronique automatique - campus de Paris",
        "École supérieure d'ingénieurs de Rennes - campus de Rennes",
        "École supérieure d'ingénieurs des travaux de la construction de Metz",
        "École supérieure d'ingénieurs des travaux de la construction de Paris",
        "École supérieure d'ingénieurs en agroalimentaire de Bretagne Atlantique - site de Brest - Bretagne INP",
        "École supérieure d'ingénieurs en agroalimentaire de Bretagne Atlantique - site de Quimper - Bretagne INP",
        "École supérieure d'ingénieurs en technologies innovantes",
        "École supérieure d'ingénieurs géomètres et topographes - Cnam",
        "École supérieure d'ingénieurs Léonard de Vinci - campus de Montpellier",
        "École supérieure d'ingénieurs Léonard de Vinci - campus de Nantes",
        "École supérieure d'ingénieurs Léonard de Vinci - campus de Paris",
        "École supérieure d'ingénieurs Réunion Océan Indien",
        "École supérieure d'électronique de l'Ouest - site Angers",
        "École supérieure d'électronique de l'Ouest - site Dijon",
        "École supérieure d'électronique de l'Ouest - site Paris-Vélizy",
        "École supérieure de biologie - biochimie - biotechnologies",
        "École supérieure de biotechnologie de Strasbourg",
        "École supérieure de chimie organique et minérale",
        "École supérieure de chimie, physique, électronique de Lyon",
        "École supérieure de fonderie et de forge",
        "École supérieure de physique et de chimie industrielles de la ville de Paris",
        "École supérieure des agricultures - campus d'Angers",
        "École supérieure des agricultures - Paris - St Quentin",
        "École supérieure des techniques aéronautiques et de construction automobile - Bordeaux",
        "École supérieure des techniques aéronautiques et de construction automobile - Laval",
        "École supérieure des techniques aéronautiques et de construction automobile - Paris-Saclay",
        "École supérieure des technologies industrielles avancées",
        "École supérieure du bois - campus de Nantes",
        "École supérieure du soudage et de ses applications",
    ]
}
