// [ProgramMPSI] Programme MPSI condensé : mathématiques, physique, chimie, informatique.
// [ProgramMPSI] Dérogation : `mpsiSubjects` (135 lignes) ne fait que retourner un catalogue statique de chapitres — exception « données statiques volumineuses » des règles de complexité Duello.
import Foundation

extension DuelloProgram {

    // MARK: MPSI / MP / PSI (programmes condensés aux matières principales)

    static func mpsiSubjects() -> [TrackSubject] {
        [
            TrackSubject(
                id: "maths",
                name: "Mathématiques",
                fullName: nil,
                icon: "function",
                chapters: [
                    chapter("logique", "Rudiments de logique et modes de raisonnement", domain: "Fondements"),
                    chapter("ensembles", "Ensembles, applications et relations", domain: "Fondements"),
                    chapter("sommes-produits", "Sommes, produits et coefficients binomiaux", domain: "Fondements"),
                    chapter("complexes", "Nombres complexes et trigonométrie", domain: "Fondements"),
                    chapter("fonctions-usuelles", "Fonctions usuelles", domain: "Analyse"),
                    chapter("calcul-derivation", "Techniques fondamentales de calcul : dérivation et primitives", domain: "Analyse"),
                    chapter("equations-differentielles", "Équations différentielles linéaires", domain: "Analyse"),
                    chapter("reels", "Nombres réels et borne supérieure", domain: "Analyse"),
                    chapter("suites", "Suites numériques", domain: "Analyse"),
                    chapter("limites-continuite", "Limites et continuité", domain: "Analyse"),
                    chapter("derivabilite", "Dérivabilité et théorème des accroissements finis", domain: "Analyse"),
                    chapter("analyse-asymptotique", "Analyse asymptotique et développements limités", domain: "Analyse"),
                    chapter("taylor", "Formules de Taylor", domain: "Analyse"),
                    chapter("integration", "Intégration sur un segment", domain: "Analyse"),
                    chapter("fonctions-deux-variables", "Fonctions de deux variables", domain: "Analyse"),
                    chapter("arithmetique", "Arithmétique dans Z", domain: "Algèbre"),
                    chapter("structures-algebriques", "Structures algébriques : groupes, anneaux, corps", domain: "Algèbre"),
                    chapter("polynomes", "Polynômes", domain: "Algèbre"),
                    chapter("fractions-rationnelles", "Fractions rationnelles", domain: "Algèbre"),
                    chapter("espaces-vectoriels", "Espaces vectoriels et sous-espaces", domain: "Algèbre"),
                    chapter("dimension", "Familles libres, bases et dimension", domain: "Algèbre"),
                    chapter("applications-lineaires", "Applications linéaires", domain: "Algèbre"),
                    chapter("matrices", "Matrices et calcul matriciel", domain: "Algèbre"),
                    chapter("systemes-lineaires", "Systèmes linéaires et pivot de Gauss", domain: "Algèbre"),
                    chapter("determinants", "Déterminants", domain: "Algèbre"),
                    chapter("prehilbertiens", "Espaces préhilbertiens réels et espaces euclidiens", domain: "Géométrie"),
                    chapter("geometrie", "Géométrie du plan et de l'espace", domain: "Géométrie"),
                    chapter("denombrement", "Dénombrement", domain: "Probabilités"),
                    chapter("probabilites", "Probabilités sur un univers fini", domain: "Probabilités"),
                    chapter("variables-aleatoires", "Variables aléatoires sur un univers fini", domain: "Probabilités"),
                ]
            ),
            TrackSubject(
                id: "physique",
                name: "Physique",
                fullName: nil,
                icon: "atom",
                chapters: [
                    chapter("mesures-incertitudes", "Mesures, incertitudes et méthodes expérimentales"),
                    chapter("oscillateur-harmonique", "Oscillateur harmonique"),
                    chapter("propagation-signal", "Propagation d'un signal et ondes progressives"),
                    chapter("interferences", "Superposition et interférences d'ondes"),
                    chapter("optique-lois", "Optique géométrique : lois de Snell-Descartes"),
                    chapter("lentilles", "Lentilles minces et instruments d'optique"),
                    chapter("monde-quantique", "Introduction au monde quantique"),
                    chapter("arqs", "Circuits électriques dans l'ARQS"),
                    chapter("premier-ordre", "Régimes transitoires : circuits du premier ordre"),
                    chapter("rlc", "Oscillateurs amortis et circuit RLC"),
                    chapter("regime-sinusoidal", "Régime sinusoïdal forcé et impédances"),
                    chapter("filtrage", "Filtrage linéaire et diagrammes de Bode"),
                    chapter("cinematique-point", "Cinématique du point"),
                    chapter("dynamique-point", "Dynamique du point et lois de Newton"),
                    chapter("energetique", "Approche énergétique du mouvement"),
                    chapter("oscillateurs-mecaniques", "Oscillateurs mécaniques et portrait de phase"),
                    chapter("particules-chargees", "Mouvement de particules chargées dans un champ"),
                    chapter("forces-centrales", "Forces centrales conservatives et mouvement képlérien"),
                    chapter("moment-cinetique", "Moment cinétique et solide en rotation"),
                    chapter("statique-fluides", "Statique des fluides"),
                    chapter("systemes-thermo", "Descriptions macroscopique et microscopique d'un système"),
                    chapter("premier-principe", "Premier principe de la thermodynamique"),
                    chapter("second-principe", "Second principe et entropie"),
                    chapter("machines-thermiques", "Machines thermiques"),
                    chapter("corps-diphase", "Corps pur diphasé et changements d'état"),
                    chapter("champ-magnetique", "Champ magnétique et forces de Laplace"),
                    chapter("induction", "Induction électromagnétique et circuit mobile"),
                ]
            ),
            TrackSubject(
                id: "chimie",
                name: "Chimie",
                fullName: nil,
                icon: "drop",
                chapters: [
                    chapter("transformations", "Transformations de la matière et états physiques"),
                    chapter("avancement", "Description d'un système physico-chimique et avancement"),
                    chapter("equilibre", "Évolution vers un état final : équilibre et quotient réactionnel"),
                    chapter("cinetique", "Cinétique chimique macroscopique"),
                    chapter("mecanismes", "Mécanismes réactionnels"),
                    chapter("atome", "Structure de l'atome et classification périodique"),
                    chapter("liaison-covalente", "Liaison covalente : schémas de Lewis et VSEPR"),
                    chapter("forces-intermoleculaires", "Polarité, forces intermoléculaires et solvants"),
                    chapter("cristaux", "Structure des solides cristallins"),
                    chapter("acide-base", "Réactions acide-base en solution aqueuse"),
                    chapter("precipitation", "Réactions de précipitation et solubilité"),
                    chapter("complexation", "Réactions de complexation"),
                    chapter("oxydoreduction", "Oxydoréduction et piles électrochimiques"),
                    chapter("diagrammes-e-ph", "Diagrammes potentiel-pH"),
                    chapter("titrages", "Dosages et titrages"),
                ]
            ),
            TrackSubject(
                id: "informatique",
                name: "Informatique",
                fullName: nil,
                icon: "chevron.left.forwardslash.chevron.right",
                chapters: [
                    chapter("python-bases", "Prise en main de Python : types et variables"),
                    chapter("structures-controle", "Structures de contrôle : tests et boucles"),
                    chapter("fonctions", "Fonctions, portée et documentation"),
                    chapter("listes", "Listes, tuples et chaînes de caractères"),
                    chapter("dictionnaires", "Dictionnaires et ensembles"),
                    chapter("recursivite", "Récursivité"),
                    chapter("correction-terminaison", "Spécification, correction et terminaison"),
                    chapter("complexite", "Complexité d'un algorithme"),
                    chapter("tris-elementaires", "Tris élémentaires : insertion et sélection"),
                    chapter("tris-recursifs", "Tris récursifs : fusion et tri rapide"),
                    chapter("dichotomie", "Recherche dichotomique"),
                    chapter("diviser-regner", "Diviser pour régner"),
                    chapter("gloutons", "Algorithmes gloutons"),
                    chapter("representation-nombres", "Représentation des nombres en machine"),
                    chapter("zeros-fonctions", "Résolution approchée d'équations : dichotomie et Newton"),
                    chapter("integration-numerique", "Calcul approché d'intégrales"),
                    chapter("euler", "Résolution numérique d'équations différentielles : méthode d'Euler"),
                    chapter("bases-de-donnees", "Bases de données relationnelles et algèbre relationnelle"),
                    chapter("sql", "Requêtes SQL"),
                    chapter("ocaml", "Programmation fonctionnelle en OCaml"),
                    chapter("types-construits", "Types construits et filtrage de motifs"),
                    chapter("recursivite-terminale", "Récursivité terminale et preuve de programmes"),
                    chapter("structures-persistantes", "Listes et structures de données persistantes"),
                    chapter("arbres", "Arbres binaires et arbres binaires de recherche"),
                    chapter("piles-files", "Piles, files et structures mutables"),
                    chapter("graphes", "Graphes : représentations et parcours"),
                    chapter("logique-propositionnelle", "Logique propositionnelle et satisfiabilité"),
                ]
            ),
        ]
    }
}
